baseURL = "https://www.gasparsantos.eu"
title = "Gaspar Santos"
## for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

languageCode = "pt-pt"

# Missing translations will default to this content language
defaultContentLanguage = "pt"

[author]
  name = "Gaspar Santos"
  license = "Gaspar Santos"

[params.info]
description = "Violinista"
title404 = "Que procura?!"

[params.assets]
#favicon = "favicon.ico"
favicon = "images/favicon.png"
customCSS = ["custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Gaspar Santos"
startYear = "2000"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan 2006"
listDateFormat = "2006, 02 Jan"
archiveDateFormat = "02 Jan"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
#sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
sidebar = ["about","sidebar_menu"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "gasparsantos_" # Twitter page username

[params.seo]
# Title Separator: - â€“ â€” Â· â€¢ * â‹† | ~ Â« Â» < >
titleSeparator = "â€¢"

[params.social]
codepen = ""
email = ""
facebook = "gasparsantosviolinista"
github = ""
gitlab = ""
instagram = ""
linkedin = ""
twitter = ""
telegram = ""
google_scholar = ""
youtube = ""

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = ""
repository = ""
branch = ""

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = ""
repository = ""

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

#[[menu.main]]
#name = "Repo"
#weight = -10
#identifier = "repository"
#url = "https://github.com/MunifTanjim/minimo"

#[blackfriday]
#hrefTargetBlank = true

[languages]
# edit this block for your own language

[languages.pt.params]
lang = "pt"
languageName = "PT"
weight = 1
description = "Gaspar Santos Violinista, website pessoal e bilheteira"
mydomain = "www.gasparsantos.eu/ ðŸ‡µðŸ‡¹"

[languages.en.params]
lang = "en"
languageName = "EN"
weight = 2
description = "Gaspar Santos Violinist, personal website and ticket office"
mydomain = "www.gasparsantos.eu/en/ ðŸ‡¬ðŸ‡§"

[languages.fr.params]
lang = "fr"
languageName = "FR"
weight = 3
description = "Gaspar Santos Violoniste, site Web personnel et billetterie"
mydomain = "www.gasparsantos.eu/fr/ ðŸ‡«ðŸ‡·"

[languages.de.params]
lang = "de"
languageName = "DE"
weight = 4
description = "Gaspar Santos Violinist, persÃ¶nliche Website und Abendkasse"
mydomain = "www.gasparsantos.eu/de/ ðŸ‡©ðŸ‡ª"

[languages.es.params]
lang = "es"
languageName = "ES"
weight = 5
description = "Gaspar Santos Violinista, web personal y taquilla"
mydomain = "www.gasparsantos.eu/es/ ðŸ‡ªðŸ‡¸"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.speakerDeck]
    disable = false
  [privacy.twitter]
    disable = false
    enableDNT = false
  [privacy.vimeo]
    disable = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

# Image processing
[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Defatult JPEG quality setting. Default is 75.
quality = 75

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"

#### MODULES
[module]
[[module.imports]]
  path = 'github.com/hugo-mods/icons'

